version: '3'
services:
  backend:
    restart: unless-stopped
    build: ./backend
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
    ports:
      - '3101:8080'

  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      args:
        - REACT_APP_BACKEND_PORT=3101
    depends_on:
      - backend
    ports:
      - '3100:80'

  postgres:
    restart: unless-stopped
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bookshelf-prod
      POSTGRES_DB: bookshelf

volumes:
  postgres_data:
    driver: local
