version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bookshelf
      - MYSQL_USER=bookshelf
      - MYSQL_PASSWORD=bookshelf
  app:
    build: .
    depends_on:
      - db
    networks:
      - default
      - nginx_default
networks:
  nginx_default:
    external:
      name: nginx_default
