version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bookshelf
      - MYSQL_USER=bookshelf
      - MYSQL_PASSWORD=bookshelf
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
