
spring:
  h2:
    console:
      enabled: true

#  datasource:
#    url: "jdbc:h2:mem:testdb"
#    driverClassName: org.h2.Driver
#    username: sa
#    password:

  datasource:
    url: jdbc:mysql://localhost:3306/bookshelf
#    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: password

  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
